Repository phovea/phovea_server, pull requests merged in 2020-01, with the labels that each got.

#89 Migrate to Python 3.7
  .circleci/config.yml
  .gitlab-ci.yml
  .travis.yml
  .yo-rc.json
  __main__.py
  deploy/Dockerfile
  deploy/Dockerfile_dev
  docs/conf.py
  phovea_server/__main__.py
  phovea_server/_plugin_parser.py
  phovea_server/_utils.py
  phovea_server/assigner.py
  phovea_server/colors.py
  phovea_server/config.py
  phovea_server/dataset.py
  phovea_server/dataset_api.py
  phovea_server/dataset_csv.py
  phovea_server/dataset_def.py
  phovea_server/dataset_specific.py
  phovea_server/dispatcher.py
  phovea_server/graph.py
  phovea_server/json_encoder.py
  phovea_server/launch.py
  phovea_server/mainapp.py
  phovea_server/mapper.py
  phovea_server/mapping_csv.py
  phovea_server/plugin.py
  phovea_server/range.py
  phovea_server/security.py
  phovea_server/server.py
  phovea_server/util.py
  phovea_server/wsgi.py
  requirements.txt
  requirements_dev.txt
  setup.py
  tests/test_range.py
  tox.ini
Labels: type: refactor

#96 Release 4.0.0
  .circleci/config.yml
  .gitignore
  .gitlab-ci.yml
  .travis.yml
  .yo-rc.json
  __main__.py
  deploy/Dockerfile
  deploy/Dockerfile_dev
  docs/conf.py
  package-lock.json
  package.json
  phovea_server/__main__.py
  phovea_server/_plugin_parser.py
  phovea_server/_utils.py
  phovea_server/assigner.py
  phovea_server/colors.py
  phovea_server/config.py
  phovea_server/dataset.py
  phovea_server/dataset_api.py
  phovea_server/dataset_csv.py
  phovea_server/dataset_def.py
  phovea_server/dataset_specific.py
  phovea_server/dispatcher.py
  phovea_server/graph.py
  phovea_server/json_encoder.py
  phovea_server/launch.py
  phovea_server/mainapp.py
  phovea_server/mapper.py
  phovea_server/mapping_csv.py
  phovea_server/plugin.py
  phovea_server/range.py
  phovea_server/security.py
  phovea_server/server.py
  phovea_server/util.py
  phovea_server/wsgi.py
  requirements.txt
  requirements_dev.txt
  setup.py
  tests/test_range.py
  tox.ini
Labels: release: major

#97 Update Debian URL from archive to current package registry in `Do…
  deploy/Dockerfile
Labels: priority: high, release: patch, type: bug
