Repository phovea/phovea_server, pull requests merged in 2020-02, with the labels that each got.

#104 Add custom Python 3 Encoder for bytes and sets
  phovea_server/__init__.py
  phovea_server/set_encoder.py
Labels: type: refactor

#106 Fix deprecated/removed Werkzeug `ProxyFix` import
  phovea_server/server.py
Labels: priority: blocker, release: patch, type: bug

#109 Release 4.0.2
  .github/CODEOWNERS
  package.json
  phovea_server/__init__.py
  phovea_server/server.py
  phovea_server/set_encoder.py
Labels: release: patch

#117 Release 4.1.0
  deploy/Dockerfile
  package.json
Labels: release: minor
