Repository phovea/phovea_server, pull requests merged in 2020-03, with the labels that each got.

#113 Add handling for NaN values and convert them to null
  phovea_server/dataset_specific.py
  phovea_server/mainapp.py
  phovea_server/util.py
  tests/test_custom_encoders.py
Labels: priority: blocker, type: bug

#120 Update requirements
  requirements.txt
  requirements_dev.txt
Labels: dependencies, priority: medium, type: refactor

#122 Release 5.0.0
  package.json
  phovea_server/dataset_specific.py
  phovea_server/mainapp.py
  phovea_server/util.py
  requirements.txt
  requirements_dev.txt
  tests/test_custom_encoders.py
Labels: release: major

#121 Remove ssh command from docker-compose-debug-partial.yml
  deploy/docker-compose-debug.partial.yml
Labels: release: minor, type: bug
